receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  awsxray:
    region: us-east-1
    endpoint: "https://xray.us-east-1.amazonaws.com"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, awsxray]